import { StyleSheet } from 'react-native';

const estiloInicial = StyleSheet.create({
  conteudoPrincipal: {
    flex: 1,
    backgroundColor: '#101010',
  },
  imagemFundo: {
    width: '100%',
    height: 780,
  },
  titulosConteudo: {
    paddingVertical: 60,
    alignItems: 'center',
  },
  textoPrincipal: {
    fontFamily: 'LaLaLandBold',
    fontSize: 120,
    textAlign: 'center',
    color: '#ffffff',
  },
  imagemPersonagens: {
    marginTop: 20,
    width: '100%',
    resizeMode: 'cover',
  },
  colorsBtn: {
    width: 310,
    height: 60,
    backgroundColor: 'red',
    marginTop: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textoInicio: {
    color: '#ffffff',
    fontSize: 30,
    fontFamily: 'SundayRomantic',
    letterSpacing: 2,
  },
  imagemFundoLogin: {
    width: '100%',
    height: 180,
    resizeMode: 'contain',
  },
  headerLogin: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoLogin: {
    fontFamily: 'SundayRomantic',
    fontSize: 47,
    textAlign: 'center',
    color: '#ffffff',
    paddingTop: 20,
  },
  conteudoForm: {
    width: '100%',
    height: 680,
    paddingVertical: 40,
    alignItems: 'center',
  },
  boxForm: {
    backgroundColor: '#1e1f22',
    width: '95%',
    height: 550,
    borderRadius: 10,
  },
  headerComponente: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
  },
  descricaoLogin: {
    color: '#cccccc',
    fontSize: 24,
    textAlign: 'center',
    fontFamily: 'SundayRomantic',
    marginTop: 15,
    padding: 12,
  },
  conteudoDados: {
    margin: 20,
    width: '100%',
    marginBottom: 80,
  },
  textoCampo: {
    color: '#cccccc',
    fontSize: 28,
    fontFamily: 'SundayRomantic',
  },
  simboloTexto: {
    color: '#f01',
    fontSize: 25,
    fontFamily: 'SundayRomantic',
  },
  inputFormulario: {
    width: '90%',
    height: 50,
    backgroundColor: '#313338',
    padding: 10,
    fontSize: 17,
    color: '#ffffff',
    marginBottom: 20,
  },
  textoEsqueceuSenha: {
    color: '#02a3f4',
    fontSize: 27,
    fontFamily: 'SundayRomantic',
    marginBottom: 20,
  },
  btnLogin: {
    width: '90%',
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  textoBtnLogin: {
    color: '#ffffff',
    fontSize: 29,
    fontFamily: 'SundayRomantic',
    textAlign: 'center',
  },
  conteudoCriarConta: {
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
    marginLeft: 5,
  },
  textoBtnConta: {
    color: '#02a3f4',
    fontSize: 22,
    fontFamily: 'SundayRomantic',
    marginLeft: 5,
  },
  btnCadastrar: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    textAlign: 'center',
  },
  textoCriarConta: {
    color: '#cccccc',
    fontSize: 22,
    flexDirection: 'row',
    fontFamily: 'SundayRomantic',
    textAlign: 'center',
  },
  boasVindas: {
    margin: 20,
  },
  textoBoasVindas: {
    fontSize: 25,
    color: '#ffffff',
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
    marginBottom: 5,
  },
  nomeUsarioEstilo: {
    color: '#cccccc',
    fontSize: 22,
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
  },
  saibaMaisContainer: {
    width: '90%',
    height: 'auto',
    marginLeft: 20,
    borderRadius: 10,
    padding: 25,
  },
  textoSaibaMais: {
    fontSize: 25,
    color: '#ffffff',
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
    textAlign: 'center',
    marginBottom: 12,
  },
  descricaoSaibaMais: {
    color: '#cccccc',
    fontSize: 20,
    fontFamily: 'SundayRomantic',
    textAlign: 'justify',
  },
  procurarConteudo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 20,
    marginBottom: 15,
  },
  inputBuscarConteudo: {
    width: '94%',
    height: 45,
    backgroundColor: '#171717',
    paddingLeft: 40,
    fontSize: 19,
    color: '#ffffff',
    fontFamily: 'SundayRomantic',
    borderRadius: 10,
  },
  iconeSearch: {
    fontSize: 20,
    position: 'absolute',
    left: 10,
    color: '#cccccc',
  },
  headerCategoria: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginEnd: 20,
    marginStart: 20,
    marginTop: 25,
  },
  textoCategoria: {
    fontSize: 22,
    color: '#ffffff',
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
  },
  tituloVerCategoria: {
    fontSize: 22,
    color: '#02a3f4',
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
  },
  cardQuizContainer: {
    marginLeft: 20,
    marginTop: 20,
    marginBottom: 30,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  cardQuizSingle: {
    width: 165,
    height: 150,
    backgroundColor: '#202020',
    marginRight: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    border: '1px solid #ffffff',
    marginBottom: 15,
  },
  imagemQuizCategoria: {
    width: 80,
    height: 80,
    resizeMode: 'cover',
  },
  textoCategoriaQuiz: {
    fontSize: 22,
    color: '#ffffff',
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
    marginTop: 20,
  },
  headerPerguntasContainer: {
    width: '100%',
    height: 90,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingEnd: 20,
    paddingStart: 20,
  },
  textoHeader:{
    fontSize: 29,
    color: '#ffffff',
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
    marginTop: 25,
  },
  containerPergunta:{
    width: '90%',
    height: 260,
    resizeMode: 'cover',
    marginLeft: 20,
    marginTop: 40,
  },
  conteudoPergunta:{
    marginLeft: 20,
    backgroundColor: '#090909',
    width: '90%',
    height: 'auto',
  },
  textoPergunta:{
    fontSize: 28,
    color: '#ffffff',
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
    textAlign: 'justify',
    padding: 15,
  },
  conteudoBotoes:{
    marginLeft: 20,
    marginTop: 20,
  },
  btnResposta:{
    width: '95%',
    height: 45,
    backgroundColor: '#020202',
    marginBottom: 10,
    justifyContent: 'center',
    paddingLeft: 20, 
  },
  textoResposta:{
    fontSize: 29,
    color: '#ffffff',
    fontFamily: 'SundayRomantic',
    textTransform: 'uppercase',
  },
  conteudoResultado:{
    flex: 1,
    paddingVertical: 80,
    alignItems: 'center',
  },
  textoResultado:{
    fontFamily: 'LaLaLandBold',
    fontSize: 65,
    color: '#cccccc',
    textTransform: 'uppercase',
    textAlign: 'center',
    marginBottom: 10,
  },
  descricaoResultado:{
    color: '#fafafa',
    fontFamily: 'SundayRomantic',
    fontSize: 28,
    padding: 6,
    textAlign: 'center',
    marginBottom: 20,
  },
  colorsBtnTentarDenovo:{
    width: 380,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoTentarNovamente:{
    color: '#ffffff',
    fontSize: 32,
    fontFamily: 'SundayRomantic',
    textAlign: 'center',
  }
});

export default estiloInicial;
